# SITE CONFIGURATION
baseurl: #"blogs"
url: "http://tandysony.com"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Tandy's Blog
  avatar: assets/img/tandy_s_tan.jpg
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "Tandy's Blog" # used by search engines

  # Header and footer text
  header_text: <h4>The best preparation for tomorrow is doing your best today.<br> -- H. Jackson Brown, Jr.</h4>
  header_text_feature_image: assets/img/fullsize/computer.jpeg
  footer_text: Tandy S. Tan <i class="fa fa-heart-o" aria-hidden="true"></i> 2018 <br> <small>Powered by <a href="https://jekyllrb.com/">Jekyll</a>

  # Icons
  rss: false
  email_address: "contact@tandysony.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "tandysony"
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/in/tandysony/" # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  portfolio: true
  search: true
  tags: true
  
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Roboto:400,400i,700,700i"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # If using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]
